##########CREATES AUCTION#########
#######ONLY FOR ADMINS###########
#######TIME FORMAT : YYYY-MM-DD
POST {{host}}/auctions
Content-Type: application/json
Authorization: {{token}}

{
  "item_id": 3,
  "start_time": "2021-01-30T14:00:00Z",
  "end_time": "2021-02-02T14:00:00Z",
  "start_price": 124.55
}
