######CREATE ITEMS#########
#######ONLY FOR ADMINS###########
POST {{host}}/items
Content-Type: application/json
Authorization: {{token}}

{
  "name": "wc stumps",
  "status": "unBiddable"
}


######LIST ALL ITEMS#########
GET {{host}}/items
Content-Type: application/json
Authorization: {{token}}


######LIST ITEMS BASED ON STATUS#########
GET {{host}}/items?status=biddable
Content-Type: application/json
Authorization: {{token}}
